volumes:
  production_mysql_data: {}
  production_mysql_data_backups: {}
  production_traefik: {}

  production_redis_data: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: papyrus_production_django
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    command: /start

  mysql:
    build:
      context: .
      dockerfile: ./compose/production/mysql/Dockerfile
    image: papyrus_production_mysql
    volumes:
      - production_mysql_data:/var/lib/mysqlql/data
      - production_mysql_data_backups:/backups
    env_file:
      - ./.envs/.production/.mysql

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: papyrus_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data


  celeryworker:
    <<: *django
    image: papyrus_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: papyrus_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: papyrus_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_mysql_data_backups:/backups:z
