#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${MYSQL_USER}" ]; then
    base_mysql_image_default_user='mysql'
    export MYSQL_USER="${base_mysql_image_default_user}"
fi
export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}"

wait-for-it "${MYSQL_HOST}:${MYSQL_PORT}" -t 30

>&2 echo 'MySQL is available'

exec "$@"
