# Generated by Django 5.1.9 on 2025-08-27 20:59

import common.model_fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('isin', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('bloomberg_code', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price_synchronization_interval', common.model_fields.CharFieldWithoutChoicesMigrations(blank=True, default='', max_length=20)),
                ('stock_exchange', common.model_fields.CharFieldWithoutChoicesMigrations(blank=True, default='', max_length=20)),
                ('timezone', common.model_fields.CharFieldWithoutChoicesMigrations(default='America/New_York', max_length=50)),
                ('price_delay_threshold', common.model_fields.CharFieldWithoutChoicesMigrations(blank=True, default='', max_length=20)),
                ('yield_synchronization_interval', common.model_fields.CharFieldWithoutChoicesMigrations(blank=True, default='', max_length=20)),
                ('yield_delay_threshold', common.model_fields.CharFieldWithoutChoicesMigrations(blank=True, default='', max_length=20)),
                ('price_source', common.model_fields.CharFieldWithoutChoicesMigrations(blank=True, default='', max_length=20)),
                ('basic_metrics_source', common.model_fields.CharFieldWithoutChoicesMigrations(blank=True, default='', max_length=20)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mangle.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LatestPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=10, max_digits=15)),
                ('price_at', models.DateTimeField()),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mangle.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=10, max_digits=15)),
                ('price_at', models.DateTimeField(db_index=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangle.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('report_at', models.DateTimeField(db_index=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangle.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('yield_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('yield_at', models.DateTimeField(db_index=True)),
                ('yield_interval', common.model_fields.CharFieldWithoutChoicesMigrations(max_length=20)),
                ('instrument', models.ForeignKey(db_comment='Duplication for speed', on_delete=django.db.models.deletion.CASCADE, to='mangle.instrument')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangle.yieldreport')),
            ],
            options={
                'verbose_name_plural': 'Yield data',
            },
        ),
        migrations.CreateModel(
            name='LastYieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('yield_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('yield_at', models.DateTimeField()),
                ('yield_interval', common.model_fields.CharFieldWithoutChoicesMigrations(max_length=20)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mangle.instrument')),
            ],
            options={
                'verbose_name_plural': 'Last yield data',
                'constraints': [models.UniqueConstraint(fields=('instrument', 'yield_interval'), name='unique_last_yield_data')],
            },
        ),
    ]
